[project]
name = "sdap-ingester"
version = "0.1.0"
description = "TBD"
readme = "README"
requires-python = ">=3.11, <3.12"

[tool.uv.workspace]
members = ["collection_manager", "common", "config_operator", "granule_ingester"]

[tool.uv.sources]
collection_manager = { workspace = true }
common = { workspace = true }
config_operator = { workspace = true }
granule_ingester = { workspace = true }

