from granule_ingester.processors.reading_processors.EccoReadingProcessor import EccoReadingProcessor
from granule_ingester.processors.reading_processors.GridReadingProcessor import GridReadingProcessor
from granule_ingester.processors.reading_processors.GridMultiBandReadingProcessor import GridMultiBandReadingProcessor
from granule_ingester.processors.reading_processors.SwathReadingProcessor import SwathReadingProcessor
from granule_ingester.processors.reading_processors.TileReadingProcessor import TileReadingProcessor
from granule_ingester.processors.reading_processors.TimeSeriesReadingProcessor import TimeSeriesReadingProcessor
