from granule_ingester.processors.reading_processors.EccoReadingProcessor import EccoReadingProcessor
from granule_ingester.processors.reading_processors.GridReadingProcessor import GridReadingProcessor
from granule_ingester.processors.reading_processors.GridMultiVariableReadingProcessor import GridMultiVariableReadingProcessor
from granule_ingester.processors.reading_processors.SwathMultiVariableReadingProcessor import SwathMultiVariableReadingProcessor
from granule_ingester.processors.reading_processors.SwathReadingProcessor import SwathReadingProcessor
from granule_ingester.processors.reading_processors.TileReadingProcessor import TileReadingProcessor
from granule_ingester.processors.reading_processors.TimeSeriesReadingProcessor import TimeSeriesReadingProcessor
from granule_ingester.processors.reading_processors.LazyLoadProcessor import LazyLoadProcessor
